# Generated by Django 4.1.1 on 2022-11-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alt_name',
            field=models.CharField(help_text='Alternative name', max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(editable=False, help_text='UUID `uuid4` random unique ID', max_length=40, null=True, unique=True),
        ),
    ]
