# Generated by Django 4.1.1 on 2022-11-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_alt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='i_alt_name',
            field=models.CharField(default='master', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='alt_name',
            field=models.CharField(default='master', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(editable=False, max_length=40, null=True, unique=True),
        ),
    ]
