# Generated by Django 4.1.1 on 2022-11-12 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Records when the object was added to the database')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Records when the object was last updated')),
                ('name', models.CharField(help_text='No empty name for a entity', max_length=150)),
                ('link', models.URLField(default=None, help_text='Unique link for a entity', unique=True)),
                ('views', models.PositiveIntegerField(default=0, help_text='Number of views of a entity')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['views'],
            },
        ),
    ]
