# Generated by Django 4.1.1 on 2022-11-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.UUIDField(default='5836257484794a068a5908fa0fb809f8', editable=False, primary_key=True, serialize=False),
        ),
    ]
