# Generated by Django 4.1.1 on 2022-11-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.UUIDField(default='4a05e0419ef04513a9216e22b6cd0a76', editable=False, primary_key=True, serialize=False),
        ),
    ]
