# Generated by Django 4.1.1 on 2022-11-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_alter_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.UUIDField(default='4160988ae2bc4cea8eca8a18981f13c8', editable=False, primary_key=True, serialize=False),
        ),
    ]
