# Generated by Django 4.1.1 on 2022-11-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_alter_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.UUIDField(default='68278e79ece64c329e6d8dd7c15d6aef', editable=False, primary_key=True, serialize=False),
        ),
    ]
