# Generated by Django 4.1.1 on 2022-11-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.UUIDField(default='2e9978a9970841458887ae749d2cfadd', editable=False, primary_key=True, serialize=False),
        ),
    ]
