# Generated by Django 4.1.1 on 2022-11-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_alter_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.UUIDField(default='f9a7c824a66b41c4890b997900b49c79', editable=False, primary_key=True, serialize=False),
        ),
    ]
