# Generated by Django 4.1.1 on 2022-11-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_alter_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.UUIDField(default='5a15b77227284913930d4935ab1de9f1', editable=False, primary_key=True, serialize=False),
        ),
    ]
