# Generated by Django 4.1.1 on 2022-11-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_alter_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.UUIDField(default='c76a711a0fc446d681dc0ce603336762', editable=False, primary_key=True, serialize=False),
        ),
    ]
