# Generated by Django 4.1.1 on 2022-11-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_alter_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.UUIDField(default='3b4f5f388ce444e290d32ab221e3afcc', editable=False, primary_key=True, serialize=False),
        ),
    ]
